version: '3.8'

services:
  db:
    image: social_media_db
    ports:
      - "8084:5432"

  social-media-service:
    image: demo_sm_api_image
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/social_media_api_db
    ports:
      - 8083:8083
    depends_on:
      - db